name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: get GTests
      run: git submodule update --init
      
    - name: Run CMake
      run: cmake -H. -B_build -DBUILD_TESTS=ON

    - name: Build tests
      run: cmake --build _build --target check

    - name: Start tests
      run: ./_build/check
