name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Directory
      run: mkdir _build

    - name: Install CMake and other build essentials
      run: sudo apt-get update && sudo apt-get install -y cmake g++ make

    - name: get GTests
      run: git submodule update --init

    - name: Run CMake
      run: cmake -H. -B_build

    - name: Build
      run: cmake --build _build --target

    - name: Without tests
      run: ./_build/MyProxyApp

